--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/mcbeany-pm-pl/NBTEditor
build-by-default: true
branches:
- master
projects:
  NBTEditor:
    path: ""
    libs:
      - src: dktapps-pm-pl/pmforms/pmforms
        version: ^2.0.0
...
