---
name: NBTEditor
version: 1.0.2
main: Mcbeany\NBTEditor\NBTEditor
api: 4.0.0

commands:
  nbteditor:
    description: Open NBTEditor Menu
    permission: nbteditor.command
    aliases: ["nbte"]

permissions:
  nbteditor.command:
    default: op
...
